### PR TITLE
Add Ubuntu dependencies to README.md

### PR DESCRIPTION
**Pull request by n3oney**
Had to figure out what I need to run it. This will make it easier for users to set up the bot.

### CODE REVIEW

**Comment by n3oney** [comment]
[Source](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md)

**Comment by gbaranski** [comment]
@n3oney I think better way would be just adding link to this [document](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md) at the bottom of README

**Comment by gbaranski** [comment]
or we can just create docker image for that, which will solve cross-platform problems.

**Comment by n3oney** [comment]
True that.

**Comment by n3oney** [comment]
> or we can just create docker image for that, which will solve cross-platform problems.

Not everyone uses docker, both would be good.

**Comment by gbaranski** [comment]
> Not everyone uses docker, both would be good.

Not everyone uses, but everyone can use regardless of the operating system they use :)

**Comment by fhodun** [comment]
I think adding this information is unnecessary

**Pull request closed without merging**
